### PR TITLE
update argument from nBits to fpSize to accomodate new datamol version

### PR DESCRIPTION
**Pull request by tsa87**
As discussed in #16, `datamol` switched from using `GetMorganFingerprintAsBitVect` to `GetMorganGenerator` in version `0.12.5`. This PR update the argument from `nBits` to `fpSize`  and set a minimum version for `datamol`.

## Changelogs
- Update default argument from `nBits` to `fpSize`.
- Fix datamol version to above 0.12.5.
---

_Checklist:_

- [x] _Was this PR discussed in an issue? It is recommended to first discuss a new feature into a GitHub issue before opening a PR._
- [x] _Add tests to cover the fixed bug(s) or the newly introduced feature(s) (if appropriate)._
- [x] _Update the API documentation if a new function is added, or an existing one is deleted._
- [x] _Write concise and explanatory changelogs above._
- [x] _If possible, assign one of the following labels to the PR: `feature`, `fix` or `test` (or ask a maintainer to do it for you)._

---

_discussion related to that PR_

### CODE REVIEW

**Review by cwognum — COMMENTED** [review]
Thanks, @tsa87 ! 

Could you also change this line: https://github.com/datamol-io/splito/blob/654e4270f54363db894c32a6ab5fca2414738017/splito/lohi/_lo.py#L81

**Comment by tsa87** [comment]
@cwognum Done!

**Comment by cwognum** [comment]
Thanks again @tsa87 ! 

Unfortunately, the test cases are failing. Could you look into this? And one more comment after a second review on my end: Could you also update [`pyproject.toml`](https://github.com/datamol-io/splito/blob/main/pyproject.toml#L43)?

**Comment by tsa87** [comment]
Thanks @cwognum! I've updated the argument for the failing test and `pyproject.toml` for datamol version.

**Comment by cwognum** [comment]
@tsa87 The failing CICD is not your mistake. It's due to https://github.com/datamol-io/splito/pull/17. 

The workaround would be to change the [CICD `doc` workflow](https://github.com/datamol-io/splito/blob/main/.github/workflows/doc.yml) to upgrade `mkdocs-jupyter` like I've done [here](https://github.com/polaris-hub/polaris/blob/main/.github/workflows/doc.yml#L38) in `polaris`. I would do it myself, but don't have write access. Sorry about that!

**Comment by cwognum** [comment]
Correction: I was actually able to do it myself! Thanks for the work, @tsa87 ! 😄

**Comment by tsa87** [comment]
Awesome @cwognum great to hear the issue was resolved!

**Pull request merged**
